### ISSUE TITLE
remember subs settings on all devices

### ISSUE THREAD

**Issue by m0ck69** [WesselKroos/remember-youtube-subtitle-settings#2]
Hello.
Is there a way to retain subtitle settings for the account regardless of where I'm watching (browser, phone, TV, etc.)? YouTube keeps defaulting to English for subtitles, and I have to change it manually every time, which is inconvenient, especially on TV.

**Comment by WesselKroos** [comment]
Sadly, there is no way to install extensions in the default browser of Android phones and TVs (Chrome).

But there is a browser in the Google Play Store with support for extensions: [Kiwi browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser). You can install that browser on your Android phone and Android TV (or Chromecast). Enable the desktop mode on the YouTube site, add the extension and it should work.
